server:
  port: 18975
spring:
  application:
    name: jdbcEntrance


eureka:
  client:
    serviceUrl:
      defaultZone: http://xxx.xxx.xxx.xxx:20303/eureka/
  instance:
    metadata-map:
      test: chaogefeng

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml

