server:
  port: 10009
spring:
  application:
    name: sparkEntrance


eureka:
  client:
    serviceUrl:
      defaultZone: locahost
  instance:
    metadata-map:
      test: enjoyyin

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml
#    register-with-eureka: false
#    fetch-registry: false